sudo: required
language: node_js
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_script:
  - find test -type d -exec chmod g+s {} \;
  - sudo chown root test/fixtures/not-owned/
  - sudo chown root test/fixtures/not-owned/not-owned.txt
after_script:
  - npm run coveralls
